services:
  docker-api:
    image: alpine/socat
    container_name: docker-api-tcp
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock
    restart: unless-stopped

  swagger-ui-nginx:
#    image: nginx:1
    image: nginx:1-alpine
    container_name: swagger-ui-nginx
    hostname: swagger-ui-nginx
    ports:
      - '8087:80'
    volumes:
      - ./swagger-ui:/swagger-ui
      - ./nginx/templates/swagger-ui.conf.template:/etc/nginx/templates/default.conf.template
    environment:
#      - DOCKER_SERVER_URL=http://192.168.88.78:2375
      - DOCKER_SERVER_URL=http://docker-api:2375
      - DOCKER_API_BASE_PATH=/v1.54/
    command: sh -c "find /swagger-ui -size +1k | grep -E '[.](yaml|yml|js|css|html)$$' | xargs gzip -k -f -6 && /docker-entrypoint.sh nginx -g 'daemon off;'"
    depends_on:
      - docker-api
